---
- name: Directory Create
  hosts: win
  tasks:
    - name: Create directory structure
      ansible.windows.win_file:
        path: C:\Automic
        state: directory
    - name: Agents Klasörünü Oluştur
      ansible.windows.win_file:
        path: C:\Automic\Agent
        state: directory
    - name: AutomationEngine Klasörünü Oluştur
      ansible.windows.win_file:
        path: C:\Automic\AutomationEngine
        state: directory
    - name: ServiceManager Klasörünü Oluştur
      ansible.windows.win_file:
        path: C:\Automic\ServiceManager
        state: directory
    - name: ServiceManagerDialog Klasörünü Oluştur.
      ansible.windows.win_file:
        path: C:\Automic\ServiceManagerDialog
        state: directory
    - name: Utility Klasörünü Oluştur
      ansible.windows.win_file:
        path: C:\Automic\Utility
        state: directory
    - name: Dizin Listesi
      set_fact:
        directory_listesi:
          - C:\Automic\AutomationEngine
          - C:\Automic\ServiceManager
          - C:\Automic\ServiceManagerDialog
          - C:\Automic\Utility
    - name: Temp oluştur
      ansible.windows.win_file:
        path: "{{ item }}/Temp"
        state: directory
      loop: "{{directory_listesi}}"
      loop_control:
        loop_var: item
    - name: bin oluştur
      ansible.windows.win_file:
        path: "{{ item }}/bin"
        state: directory
      loop: "{{directory_listesi}}"
      loop_control:
        loop_var: item
    - name: Utility db Klasörünü Oluştur
      ansible.windows.win_file:
        path: C:/Automic/Utility/db
        state: directory