---
- name: MSSQL Connect
  hosts: win
  tasks:
    - name: MSSQL Bilgileri
      set_fact:
        mssql_connection_info:
          host: "192.168.1.23"
          port: "1965"
          database: "master"
          username: "automic"
          password: "Asd123qss!"

    - name: MSSQL Connect
      mssql_query:
        server: "{{ mssql_connection_info.host }}"
        port: "{{ mssql_connection_info.port }}"
        database: "{{ mssql_connection_info.database }}"
        state: present
        login_user: "{{ mssql_connection_info.username }}"
        login_password: "{{ mssql_connection_info.password }}"
        query: "Your SQL Query Here" 