---
- name: Automic Klasör Oluşturma
  hosts: all
  tasks:
    - name: Automic Klasörünü Oluştur
      file:
        path: C:/Automic
        state: directory
    - name: Agents Klasörünü Oluştur
      file:
        path: C:/Automic/Agent
        state: directory
    - name: AutomationEngine Klasörünü Oluştur
      file:
        path: C:/Automic/AutomationEngine
        state: directory
    - name: ServiceManager Klasörünü Oluştur
      file:
        path: C:/Automic/ServiceManager
        state: directory
    - name: ServiceManagerDialog Klasörünü Oluştur.
      file:
        path: C:/Automic/ServiceManagerDialog
        state: directory
    - name: Utility Klasörünü Oluştur
      file:
        path: C:/Automic/Utility
        state: directory
    - name: Dizin Listesi
      set_fact:
        directory_listesi:
          - AutomationEngine
          - ServiceManager
          - ServiceManagerDialog
          - Utility
    - name: Temp oluştur
      file:
        path: C:/Automic/{{ item }}/Temp
        state: directory
      loop: "{{directory_listesi:}}"
      loop_control:
        loop_var: item
    - name: bin oluştur
      file:
        path: C:/Automic/{{ item }}/bin
        state: directory
      loop: "{{directory_listesi:}}"
      loop_control:
        loop_var: item
    - name: Utility db Klasörünü Oluştur
      file:
        path: C:/Automic/Utility/db
        state: directory
        