---
- name: DB Script Run
  hosts: win
  tasks:
    - name: DB Create Script
      shell: |
        sqlcmd -S 192.168.1.1 -U automic -P Asd123qss! -d automic -i /path/to/your/script.sql
      args:
        executable: /bin/bash
      become: yes