---
- name: Update INI File
  hosts: win
  tasks:
    - name: Update System= Value in INI File
      win_lineinfile:
        path: "C:/Automic/AutomationEngine/bin/ucsrv.ini"
        regexp: '^system='
        line: 'system=emir'
    - name: Update cp= Value in INI File
      win_lineinfile:
        path: "C:/Automic/AutomationEngine/bin/ucsrv.ini"
        regexp: '^cp='
        line: 'cp=emir'
    - name: Update jdbc Value in INI File
      win_lineinfile:
        path: "C:/Automic/AutomationEngine/bin/ucsrv.ini"
        regexp: '^sqlDriverConnect=jdbc:'
        line: 'sqlDriverConnect=jdbc:kandemir'
    - name: Update ODBCVAR Value in INI File
      win_lineinfile:
        path: "C:/Automic/Utility/bin/ucybdbld.ini"
        regexp: '^sqlDriverConnect=ODBCVAR='
        line: 'ssqlDriverConnect=ODBCVAR=denemedeneme'


      
      