---
  - name: Configuring .ini File
    hosts: all
    vars:
      new_driverConnect: 'denemedeneme'


    tasks:
      - name: Configure AutomationEngine .ini
        ansible.builtin.lineinfile
          path: C:/Automic/AutomationEngine/bin/ucsrv.ini
          regexp: '^sqlDriverConnect='
          line: sqlDriverConnect={{newnew_driverConnect}} 