---
- name: Birinci asamayi calistir
  import_playbook: playbook_1.yml

- name: Ikinci asamaya gecmeden once bekle
  import_playbook: wait_playbook.yml

- name: Ikinci asamayi calistir
  import_playbook: playbook_2.yml
