---
- name: Playbooklar Arasi Bekleme Adimi
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Diger playbooka gecmeden once 60 saniye (1 dakika) bekle
      ansible.builtin.pause:
        seconds: 60
